version: 2

references:
  environment: &environment
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  spotless:
    <<: *environment
    steps:
      - checkout
      - run: ./gradlew spotlessCheck

  build:
    <<: *environment
    steps:
      - checkout
      - run: ./gradlew publish

  ## Require an AWS account, and take some money to launch EMR, so it doesn't work now.
  run_example:
    <<: *environment
    steps:
      - checkout
      - run: ./example/run.sh

workflows:
  version: 2

  merge-before:
    jobs:
      - build
      - spotless

  
